version: '3.1'

services:
  backend:
    image: 'tour_image'
    container_name: 'tour-kazakh'
    depends_on:
      - pgdb
    environment:
      - SERVER_PORT=3030
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Master
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/tour_database
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    ports:
      - 8000:3030

  pgdb:
    image: 'postgres'
    container_name: 'pg-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Master
      - POSTGRES_DB=tour_database
    ports:
      - 2345:5432